// Copyright 2024 LTKSK (@LTKSK)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

// generated by `python3 util/vial_generate_keyboard_uid.py` command.
#define VIAL_KEYBOARD_UID {0x2C, 0x01, 0xD6, 0xAE, 0x4A, 0x88, 0xCB, 0x7F}
#define VIAL_UNLOCK_COMBO_ROWS { 3, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 6 }

// 容量削減のため
// @see https://zenn.dev/koron/articles/98324ab760e83a
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

/* EEPROM Driver Configuration */
#define WEAR_LEVELING_LOGICAL_SIZE 8192 /*8192 is just an example*/
#define WEAR_LEVELING_BACKING_SIZE 16384 // (WEAR_LEVELING_LOGICAL_SIZE * 2)

// 合わせてroles.mkにMUSIC_ENABLE=noが必要
#define NO_MUSIC_MODE
