// generated by `python3 util/vial_generate_keyboard_uid.py` command.
#define VIAL_KEYBOARD_UID {0x0B, 0x21, 0x55, 0x99, 0x26, 0x72, 0xDD, 0x46}
#define VIAL_UNLOCK_COMBO_ROWS { 3, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 6 }