// Copyright 2024 LTKSK (@LTKSK)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// generated by `python3 util/vial_generate_keyboard_uid.py` command.
#define VIAL_KEYBOARD_UID {0x98, 0xC8, 0x73, 0x11, 0x6C, 0x5B, 0x70, 0x97}
#define VIAL_UNLOCK_COMBO_ROWS { 3, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 6 }

#define ADNS5050_SCLK_PIN         F7
#define ADNS5050_SDIO_PIN         F6
#define ADNS5050_CS_PIN           B1

// これがないと直感と真逆に動く
#define POINTING_DEVICE_ROTATION_180
