// Copyright 2024 LTKSK (@LTKSK)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT


// generated by `python3 util/vial_generate_keyboard_uid.py` command.
#define VIAL_KEYBOARD_UID {0x98, 0xC8, 0x73, 0x11, 0x6C, 0x5B, 0x70, 0x97}
#define VIAL_UNLOCK_COMBO_ROWS { 3, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 6 }
